version: '3'
services:
#  web:
#    build: ./docker-nginx
#    ports:
#        - 80:80
#    depends_on:
#        - app
#    volumes:
#        - ./:/var/www/html
#        - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
#    links:
#        - app  
  app:
    build: ./php
#    depends_on:
#        - db
#    links:
#        - db
    volumes:
        - ./:/var/www/html
